version: "3"
services:
  mysql:
    image: mariadb
    ports:
      - 3306:3306
    command:
      - mariadbd
      - --log-bin=mysql-bin
      - --binlog-format=ROW
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database

  zookeeper:
    image: bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.2
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - 8080:8080

  kafka-connect:
    # image: confluentinc/cp-kafka-connect
    # platform: linux/amd64
    # image: bitnami/kafka:2.5.0
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    volumes:
      # - './debezium-connector-mysql:/etc/kafka-connect/jars/debezium-connector-mysql'
      - './connect.properties:/etc/kafka/connect.properties'
      - './debezium-mysql-source-connector.properties:/etc/kafka/debezium-mysql-source-connector.properties'
      - './debezium-postgres-sink-connector.properties:/etc/kafka/debezium-postgres-sink-connector.properties'
    depends_on:
      - zookeeper
      - kafka
    command:
      - 'connect-standalone'
      - '/etc/kafka/connect.properties'
      - '/etc/kafka/debezium-mysql-source-connector.properties'
      - '/etc/kafka/debezium-postgres-sink-connector.properties'
    environment:
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
